name: Publish to npm

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup Bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Build the project
      - name: Build
        run: bun run build
      
      # Publish to npm
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }} 